// Sample financial data for different months
export const monthlyData = {
  "2025-05": [
    {
      id: 1,
      memberName: "Goyani Hitesh K.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 2,
      memberName: "Vaghani Takshil P.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 3,
      memberName: "Goyani Haresh N.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 4,
      memberName: "Goyani Om H.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 5,
      memberName: "Mendpara Ronil R.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 6,
      memberName: "Mendpara Nancy R.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 7,
      memberName: "Goyani Prakash",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 8,
      memberName: "Goyani Hery A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 9,
      memberName: "Goyani ashok K.",
      installment: 1000,
      amount: 10000,
      interest: 125,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1125,
    },
    {
      id: 10,
      memberName: "Goyani Aarh A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 11,
      memberName: "Goyani Mahendra M.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 12,
      memberName: "Bhisara Chetan H.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 20000,
      newWithdrawal: 0,
      total: 1250,
      highlighted: true,
    },
    {
      id: 13,
      memberName: "Bhisara Daksh C.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 20000,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 14,
      memberName: "Bhisara Kalpesh H.",
      installment: 1000,
      amount: 5000,
      interest: 63,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1063,
      highlighted: true,
    },
    {
      id: 15,
      memberName: "Bhisara Himmatbhai D.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 20000,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 16,
      memberName: "Bhisara Mahesh B.",
      installment: 1000,
      amount: 10000,
      interest: 125,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1125,
    },
  ],
  "2025-04": [
    {
      id: 1,
      memberName: "Goyani Hitesh K.",
      installment: 1000,
      amount: 5000,
      interest: 62,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1062,
    },
    {
      id: 2,
      memberName: "Vaghani Takshil P.",
      installment: 1000,
      amount: 10000,
      interest: 125,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1125,
    },
    {
      id: 3,
      memberName: "Goyani Haresh N.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 4,
      memberName: "Goyani Om H.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 5,
      memberName: "Mendpara Ronil R.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 6,
      memberName: "Mendpara Nancy R.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 7,
      memberName: "Goyani Prakash",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 8,
      memberName: "Goyani Hery A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 9,
      memberName: "Goyani ashok K.",
      installment: 1000,
      amount: 15000,
      interest: 188,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1188,
    },
    {
      id: 10,
      memberName: "Goyani Aarh A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 11,
      memberName: "Goyani Mahendra M.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 12,
      memberName: "Bhisara Chetan H.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 25000,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 13,
      memberName: "Bhisara Daksh C.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 25000,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 14,
      memberName: "Bhisara Kalpesh H.",
      installment: 1000,
      amount: 7500,
      interest: 94,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1094,
    },
    {
      id: 15,
      memberName: "Bhisara Himmatbhai D.",
      installment: 1000,
      amount: 25000,
      interest: 312,
      fine: 0,
      withdrawal: 25000,
      newWithdrawal: 0,
      total: 1312,
    },
    {
      id: 16,
      memberName: "Bhisara Mahesh B.",
      installment: 1000,
      amount: 15000,
      interest: 188,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1188,
    },
  ],
  "2025-03": [
    {
      id: 1,
      memberName: "Goyani Hitesh K.",
      installment: 1000,
      amount: 15000,
      interest: 188,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1188,
    },
    {
      id: 2,
      memberName: "Vaghani Takshil P.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 3,
      memberName: "Goyani Haresh N.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 4,
      memberName: "Goyani Om H.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 5,
      memberName: "Mendpara Ronil R.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 6,
      memberName: "Mendpara Nancy R.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 7,
      memberName: "Goyani Prakash",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 8,
      memberName: "Goyani Hery A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 9,
      memberName: "Goyani ashok K.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
    {
      id: 10,
      memberName: "Goyani Aarh A.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 11,
      memberName: "Goyani Mahendra M.",
      installment: 1000,
      amount: 0,
      interest: 0,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1000,
    },
    {
      id: 12,
      memberName: "Bhisara Chetan H.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 30000,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 13,
      memberName: "Bhisara Daksh C.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 30000,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 14,
      memberName: "Bhisara Kalpesh H.",
      installment: 1000,
      amount: 10000,
      interest: 125,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1125,
    },
    {
      id: 15,
      memberName: "Bhisara Himmatbhai D.",
      installment: 1000,
      amount: 30000,
      interest: 375,
      fine: 0,
      withdrawal: 30000,
      newWithdrawal: 0,
      total: 1375,
    },
    {
      id: 16,
      memberName: "Bhisara Mahesh B.",
      installment: 1000,
      amount: 20000,
      interest: 250,
      fine: 0,
      withdrawal: 0,
      newWithdrawal: 0,
      total: 1250,
    },
  ],
}